name: Maven Deploy
on:
  workflow_dispatch:
    inputs:
      description: 'The branch to build'
      required: true
      version:
        description: 'Release Version (Ex: 1.0.0)'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: Get Tag Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          java-package: 'jdk'
          check-latest: true
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set Release Version
        run: |
          echo "Publish version: $RELEASE_VERSION to Nexus Repository Manager"
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Sonatype
        run: mvn -B -U deploy --file pom.xml --settings settings.xml
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}